apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: raeci51fn-python 
  janus-idp.io/tekton: raeci51fn-python
  backstage.io/kubernetes-id: raeci51fn-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: raeci51fn-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  